sudo: required

language: node_js

node_js:
  - "8"

addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

services:
  - xvfb

install:
  - npm install

script:
  - npm test
