sudo: required

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

# Make chrome browser available for testing
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

services:
  - xvfb

install:
  - npm install

script:
  - npm test
